name: GitHub Actions Dry Run

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 加上這行允許 push Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Echo dry run
        run: echo "目前未設定自動建置與發佈內容，僅作為初始化測試"

      - name: Deploy empty placeholder (safe fallback)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./placeholder
          enable_jekyll: false
